services:
  chat-ai:
    build:
      context: .
      dockerfile: Dockerfile.chat
    env_file:
      - ./.env
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    command: ["python", "-m", "streamlit", "run", "app_ai_chat.py", "--server.address=0.0.0.0", "--server.port=8501"]